// Generated by Melange
'use strict';

var Caml_array = require("melange/lib/js/caml_array.js");
var PgsqlParser = require("pgsql-parser");

function selectStmt(param_0) {
  return {
          TAG: /* SelectStmt */0,
          _0: param_0
        };
}

function updateStmt(param_0) {
  return {
          TAG: /* UpdateStmt */1,
          _0: param_0
        };
}

var test = PgsqlParser.parse("\n  SELECT\n    a.id,\n    b.id,\n    a.name,\n    b.name\n  FROM\n    table_a AS a\n    JOIN table_b AS b ON b.a_id = a.id\n  WHERE\n    a.id = 42\n  LIMIT 50\n  ;\n\n  SELECT\n    *\n  FROM\n    blah\n  ;\n\n  UPDATE\n    some_table\n  SET\n    some_column = \"some value\",\n    another_column = 27\n  WHERE\n    id = 42\n  ;\n\n  INSERT INTO something(id, col1, col2)\n  VALUES (123, \"foo\", \"bar\")\n  ;\n");

// console.log(test);

// console.log(Caml_array.get(test, 0));

// console.log(Caml_array.get(test, 0).RawStmt);

console.log(Caml_array.get(test, 0).RawStmt.stmt);

console.log(Caml_array.get(test, 0).RawStmt.stmt.SelectStmt);

// var y = Caml_array.get(test, 0).RawStmt.stmt;

// if (y.TAG === /* SelectStmt */0) {
//   console.log([
//         "Select Statement",
//         y._0
//       ]);
// } else {
//   console.log([
//         "Update Statement",
//         y._0
//       ]);
// }

exports.selectStmt = selectStmt;
exports.updateStmt = updateStmt;
exports.test = test;
/* test Not a pure module */
